id: I57767588
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T18:29:19+00:00'
last_modified: '2022-06-08T06:44:19.127768+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4PD1174
  title: རྡོར་སེམས་ཐུགས་ཀྱི་སྒྲུབ་པའི་སྔོན་འགྲོའི་ཟིན་བྲིས་རྣམ་གྲོལ་ཐེམ་སྐས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C652:
      image_group_id: I4PD1539
      title: ''
      total_pages: 388
      order: 1
      base_file: C652.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
