id: P006770
initial_creation_type: ocr
source_metadata:
  id: bdr:W4PD1174
  title: རྡོར་སེམས་ཐུགས་ཀྱི་སྒྲུབ་པའི་སྔོན་འགྲོའི་ཟིན་བྲིས་རྣམ་གྲོལ་ཐེམ་སྐས།
  author: ''
  volumes:
    3c9f57b4518d4be090226d014180de3a:
      image_group_id: I4PD1539
      title: ''
      volume_number: 1
      total_pages: 388
      base_file: v001.txt
